language: dart
dart:
  - stable
  - dev
  - "2.0.0"
dart_task:
  - test: --platform vm
  - test: --platform chrome
sudo: required # https://github.com/travis-ci/travis-ci/issues/8836#issuecomment-356362524
